### ISSUE TITLE
Ubuntu20.04， docker部署仿真teeu环境时，运行authmanager报错；

### ISSUE THREAD

**Issue by pmpleader** [secretflow/authmanager#10]
运行occlum run /bin/auth-manager --config_path /host/config.yaml

错误如下：
occlum-pal: Failed to create enclave with error code 0x2004: Unknown SGX error (line 152, file src/pal_enclave.c)

帮看看是哪里的问题，谢谢；

**Comment by yuki252111** [comment]
咱这边是用simulation模式启动的么 
这个错误看着是production模式 但是由于机器并非sgx机器导致报的错误

**Comment by pmpleader** [comment]
@yuki252111 谢谢；
我是按照下面的操作启动的：
<img width="1116" alt="image" src="https://github.com/secretflow/authmanager/assets/24772933/eb5f42d7-99d5-4c13-a269-72e1faec6b7b">
是需要在哪个配置文件中再设置一下simulation模式吗？

**Comment by yuki252111** [comment]
咱这边按照这个流程做好了之后 是不是修改过文件

**Comment by pmpleader** [comment]
没有修改过文件啊；

我就是先执行第1步，下载docker文件，然后执行第2步进入docker镜像；
再执行第4步启动服务：occlum run /bin/auth-manager --config_path /host/config.yaml 报错；

其中第三部提到的config.yaml中的enable_tls我看值就是false，所有没有修改；

**Comment by yuki252111** [comment]
看报错是创建enclave失败，但我这边无法复现这个问题，可否有进一步的信息提供
按照我们的经验 一般enclav创建失败要么是production模式的问题、要么就是修改了文件之后没有进行occlum build -f

**Comment by pmpleader** [comment]
在运行docker文件docker run -it --net host secretflow/authmanager-ubuntu-sim-release:latest时，有个提示：
![image](https://github.com/secretflow/authmanager/assets/24772933/be38618b-640c-4b39-a012-41014cd3707e)
帮看看和这个有关系吗？还是需要修改哪里吗？

**Comment by pmpleader** [comment]
我是想测试一下模拟环境下AuthManager的运行，目前这台机器上的sgx还没有开通；

**Comment by yuki252111** [comment]
没有关系的  这个报错可以忽略

**Comment by pmpleader** [comment]
恩，那其他的就是执行了那3步；
对了，occlum run /bin/auth-manager --config_path /host/config.yaml 在docker里面运行行命令时，报哪个错误后，我发现 /bin/auth-manager 和  /host/config.yaml 都不存在，我做了调整，如下：occlum run /home/root/image/bin/auth-manager --config_path /home/root/image/host/config.yaml，其中config.yaml是从/home/root目录下拷贝到image/host目录下的；同样还是报错；
我测试用的机器是新装的Ubuntu20.04，直接拉下来Auth-Manager的镜像测试的，按理说镜像里面的环境都具备的，不应该出问题啊；

**Comment by pmpleader** [comment]
那还可能是我这边哪里的环境和您的不一样导致的吗？

**Comment by pmpleader** [comment]
对了，我直接使用镜像就可以吧？不用再装sgx的驱动吧？

**Comment by yuki252111** [comment]
无需调整哈  occlum 默认的/ 在image目录下，所以 /bin/auth-manager 实际的路径是/image/bin/auth-manager；除了image之外的其他位置默认/host下，所以/host/config.yaml 实际是config.yaml这个文件

**Comment by pmpleader** [comment]
恩，谢谢了；有时间的话，您那边帮忙对docker镜像直接执行那3步，测试下，看看是否报错呢;

**Comment by yuki252111** [comment]
这边现在直接执行可以正常启动了么

**Comment by pmpleader** [comment]
不能呢，还是那个错误；我重新下载了docker镜像，重新运行那三条命令，还是报错；奇怪了；

<img width="784" alt="image" src="https://github.com/secretflow/authmanager/assets/24772933/4187d590-a7c6-48de-ba36-64fcfce44c37">

**Comment by pmpleader** [comment]
换一台机器后解决了，谢谢；

**Comment by zhouaihui** [comment]
https://github.com/occlum/occlum#how-to-use

hi， @pmpleader ，可以分别发一下你使用的两台机器host os的版本吗

**Comment by pmpleader** [comment]
![image](https://github.com/secretflow/authmanager/assets/24772933/ec60b38e-69c4-4651-8dcb-3982297437b2)
这是我当时有问题的机器的配置；你的具体是什么问题？

**Comment by pmpleader** [comment]
@zhouaihui 主要是cpu型号导致我的问题，后来我换了一台机器；
![image](https://github.com/secretflow/authmanager/assets/24772933/c922fd80-58ad-42ff-81d7-ecc5a3429399)
