### ISSUE TITLE
没找到secretflow/authmanager-dev-ubuntu:0.1.0b0镜像

### ISSUE THREAD

**Issue by LeoneChen** [secretflow/authmanager#12]
https://github.com/secretflow/authmanager/blob/fbfea7fe0fa8d3fff9e1377f1ec2da66fe152aa2/sgx2-env#L4

我没有在 https://hub.docker.com/u/secretflow 找到任何关于`secretflow/authmanager-dev-ubuntu:0.1.0b0`的镜像

**Comment by yuki252111** [comment]
maybe you can use image secretflow/authmanager-ubuntu-ci:0.1.0b

**Comment by LeoneChen** [comment]
ok
